# Generated by Django 5.1.2 on 2024-11-03 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boleto",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
            ),
        )
    ]
